### ISSUE TITLE
Searches not working properly

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/docs-v1#101]
Searches in the docs need to be fixed.

For example, the "Secrets Manager" page which has the name in the title, and the words "Secrets Manager" are repeated in a few places:

![image](https://user-images.githubusercontent.com/11074908/236168513-4906fdae-8779-4eaa-a0c0-ff2d0bb9b4ae.png)

However, the results displayed when I search for it are not related:

![image](https://user-images.githubusercontent.com/11074908/236168712-eafda7ec-5080-4077-b5ff-fe5ced6b2e19.png)

**Comment by aniketkatkar97** [comment]
@pmbrull can this be related to how the indexes are created?

**Comment by pmbrull** [comment]
most probably. I'll need to take a look

**Comment by aniketkatkar97** [comment]
Fixed in #125
