### ISSUE TITLE
Custom component for connector header and list

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/docs-v1#194]
We have 2 pages that could use improvement

1. Connector list page https://docs.open-metadata.org/v1.2.x/connectors
![image](https://github.com/open-metadata/docs-v1/assets/35870520/392e2315-f479-47ed-ad80-21efd0c2dc6e)

2. Each connector landing
![image](https://github.com/open-metadata/docs-v1/assets/35870520/0593e2ea-5639-451e-993f-0410ec4da9c2)

We should figure out how to organize the information at the top and add who developed the component (Collate vs. Community) to also align expectations.

Instead of a table, we could wrap this into something a bit more polished. Then, a smaller version could be used for the connector list.

A good example is this https://greatexpectations.io/expectations

![image](https://github.com/open-metadata/docs-v1/assets/35870520/0065a237-8a3b-46e6-86e6-8e28f59d6ca0)

**Comment by pmbrull** [comment]
<img width="764" alt="image" src="https://github.com/open-metadata/docs-v1/assets/35870520/b4e344c7-92c6-4350-9499-906f16c81a17">

**Comment by aniketkatkar97** [comment]
completed in #235
