### ISSUE TITLE
Docs improvements

### ISSUE THREAD

**Issue by sureshms** [open-metadata/docs-v1#20]
cc @harshach 

- [ ] We should use a subtle color similar to GitHub for quoted strings. Currently, it is too bright and in your face. 
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/1417689/208189160-1e4f68e8-59a9-4a03-a8b2-df96f8540d5f.png">

- [ ] The comment icon is not aligned with the text 
<img width="489" alt="image" src="https://user-images.githubusercontent.com/1417689/208189447-262709cd-907b-49cb-b6a1-f3a18b542473.png">

- [ ] Icons for thumbs up and down are too big and don't align with the text 
<img width="488" alt="image" src="https://user-images.githubusercontent.com/1417689/208189526-1a5093e6-da67-40e4-8461-007ae53ee499.png">

- [ ] Heading sizes are too big and should be reduced
- [ ] Expand a topic on the left panel and click it. Now the other items can't be clicked. In this example, I can't click SingleStore or any other topic on the left panel.
<img width="301" alt="image" src="https://user-images.githubusercontent.com/1417689/208189973-19259a07-63cb-4390-b3f1-c1eb2033bb6a.png">

**Comment by pmbrull** [comment]
closing this since most of that has been changed in the new docs
