### ISSUE TITLE
Version functionality improvements for usability of old links

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/docs-v1#291]
The existing older documentation link should redirect to the latest version page. For Example, if we visit this link https://docs.open-metadata.org/v1.1.x/how-to-guides/quick-start-guide-for-admins/how-to-ingest-metadata/delete-service-connection it should redirect to the latest version.

**Comment by aniketkatkar97** [comment]
- [x] Show the "latest" string in place of the version for the version marked as latest for them to be used as permalinks/bookmarks
