### ISSUE TITLE
In Airflow pipeline Lineage backend and operator page is not working.

### ISSUE THREAD

**Issue by MilanBariya** [open-metadata/docs-v1#58]
It's giving error when we open that page.
 ```
Unhandled Runtime Error
NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
``` 
<img width="1038" alt="Screenshot 2023-04-06 at 5 17 14 PM" src="https://user-images.githubusercontent.com/52292922/230367539-4429ddd2-c5e6-4941-b81c-019afbbfb870.png">

**Comment by aniketkatkar97** [comment]
This turned out to be the content issue. Because of the same syntax, the content inside the fence conflicted with the rendering functionality of the `MarkDoc` tags. The concerned content was removed [here](https://github.com/open-metadata/OpenMetadata/pull/11181) as it was just a template code.
