### ISSUE TITLE
UI: Release ordering + listing

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/docs-v1#88]
- Releases should be ordered based on the recent release first
- Releases should have stable / beta tags

![image](https://user-images.githubusercontent.com/40225091/234367545-a50b5e69-aca0-4096-ad8c-99e07af9116f.png)

reference image:
![image](https://user-images.githubusercontent.com/40225091/234367582-3825d05f-d414-41ac-a46f-e66f1049d836.png)

**Comment by aniketkatkar97** [comment]
@harshach any thoughts on adding `stable/beta` tags in the version selection dropdown options?
