### ISSUE TITLE
Docs V1 Feedback

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/docs-v1#93]
Let's track here any improvements for the v1 docs

**Comment by harshach** [comment]
- [ ] we need a better contrasting background color for certain terms we are calling out. These are not code but highlighters 
<img width="554" alt="image" src="https://user-images.githubusercontent.com/38649/234653991-443edc14-dfa7-4616-b923-bd8bc1f9074e.png">

**Comment by pmbrull** [comment]
- [ ] The image component should allow us to choose the size

**Comment by aniketkatkar97** [comment]
- [ ] Collapsing the side panel re scrolls the page every time

https://user-images.githubusercontent.com/51777795/234765911-5524f800-2144-440f-afab-f7a878acc889.mov

**Comment by aniketkatkar97** [comment]
- [ ] Add tracking pixel changes

**Comment by ayush-shah** [comment]
- [ ] not able to see robots.txt or sitemap.xml
the path should be:
https://docs.open-metadata.org/robots.txt
https://docs.open-metadata.org/sitemap.xml

- [ ] Expected:
The whole highlighted div should take us to the page
Actual:
when i click on blue box, it doesn’t take me to the page ( empty side / descriptions )
when i click on heading line, it takes me to the page..

![image](https://user-images.githubusercontent.com/40225091/235608684-15cb6062-94ac-4d22-ba2c-de580cdeb9b5.png)

**Comment by aniketkatkar97** [comment]
- [ ] Selected version flickers after each page changes

https://user-images.githubusercontent.com/51777795/235683245-7e72dfe5-2e1a-48f6-a581-f98faca3c8b5.mov

**Comment by aniketkatkar97** [comment]
- [ ] Auto-scroll while typing in the search box

https://user-images.githubusercontent.com/51777795/236186828-09c4b7a1-ca2e-4336-b935-4519bc6f1123.mov
